name: lengau-tox
version: 4.12.1
summary: Command line driven CI frontend and development task automation tool.
# noinspection YAMLSchemaValidation
# https://youtrack.jetbrains.com/issue/PY-58754
description: |
  tox is a generic virtual environment management and test command line tool you can use for:

  * checking your package builds and installs correctly under different environments (such as different Python implementations, versions or installation dependencies),
  * running your tests in each of the environments with the test tool of choice,
  * acting as a frontend to continuous integration servers, greatly reducing boilerplate and merging CI and shell-based testing.


confinement: classic
base: core22
# The base that the builds run on - allows building for other architectures
build-base: core22
compression: lzo
contact: https://github.com/lengau/tox-snap/issues
issues:
  - https://github.com/lengau/tox-snap/issues
  - https://github.com/tox-dev/tox/issues
source-code: https://github.com/tox-dev/tox
website: https://github.com/tox-dev/tox

environment:
  PATH: "/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

parts:
  libs:
    plugin: nil
    stage-packages:
    - libpython3-stdlib
    - libpython3.10-minimal
    - libpython3.10-stdlib
    - python3.10-minimal
    - python3.10
    build-attributes: [enable-patchelf]
  tox:
    after: [libs]
    plugin: python
    source: https://github.com/tox-dev/tox
    source-type: git
    source-tag: 4.12.1
    source-depth: 1
    build-attributes: [enable-patchelf]

apps:
  tox:
    command: bin/python3 $SNAP/bin/tox
    plugs:
      - home
      - network
      - removable-media
