name: Snap upstream releases

on:
  workflow_dispatch:  # Allow manual run
  workflow_call: # Allow calling from another workflow
  schedule:
    - cron: "0 6 * * *"  # Every day at 06:00 UTC

concurrency: ${{ github.workflow }}

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  sync-gh-releases:
    name: Sync upstream releases
    uses: lengau/snappify/.github/workflows/sync-gh-releases.yaml@main
    with:
      upstream_repository: tox-dev/tox
      max_releases: 1
      prep_script: tools/prep_release.sh
  do-releases:
    name: Release ${{ matrix.tag }}
    runs-on: ubuntu-latest
    needs: sync-gh-releases
    if: ${{ needs.sync-gh-releases.outputs.release_tags != '[]' && needs.sync-gh-releases.outputs.release_tags != '' }}
    strategy:
      max-parallel: 1
      matrix:
        tag: ${{ fromJSON(needs.sync-gh-releases.outputs.release_tags) }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Codespell ${{ matrix.tag }}
          body: See upstream release at https://github.com/tox-dev/tox/releases/tag/${{ matrix.tag }}
          prerelease: ${{ contains(matrix.tag, 'pre') }}
          tag_name: ${{ matrix.tag }}
